[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/2026-politique-et-ecosysteme/index.html"
to = "/gt/2026-politique-et-ecosysteme/"

[[redirects]]
from = "/projets/index.html"
to = "/gt/"

[[redirects]]
from = "/gt/aarse-13/index.html"
to = "/gt/localisation/aarse-13/"

[[redirects]]
from = "/expositions/index.html"
to = "/projections/"

[[redirects]]
from = "/personnes/aarse/index.html"
to = "/personnes/elodie-boin-zanchi/"

[[redirects]]
from = "/2026-chantier-cinema/index.html"
to = "/gt/2026-chantier-cinema/"

[[redirects]]
from = "/agenda/2026/adieu-sauvage/index.html"
to = "/agenda/2026/vraidevrai-marseille-2026/"

[[redirects]]
from = "/personnes/aarse/actualites/index.html"
to = "/personnes/elodie-boin-zanchi/actualites/"

[[redirects]]
from = "/expositions/archives-expositions/index.html"
to = "/projections/archives-expositions/"

[[redirects]]
from = "/gt/aarse-06/index.html"
to = "/gt/localisation/aarse-06/"

[[redirects]]
from = "/agenda/2026/adieu-sauvage/projection-debat-againt-the-tide/index.html"
to = "/agenda/2026/vraidevrai-marseille-2026/varado/"

[[redirects]]
from = "/ceci-est-un-test/index.html"
to = "/aarse-06/"

[[redirects]]
from = "/archives-expositions/index.html"
to = "/projections/archives-expositions/"

